services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Migrify\VendorPatches\:
        resource: "../src"
        exclude:
            - "../src/HttpKernel/*"
            - "../src/ValueObject/*"

    SebastianBergmann\Diff\Output\UnifiedDiffOutputBuilder:
        arguments:
            $addLineNumbers: true

    SebastianBergmann\Diff\Differ:
        arguments:
            $outputBuilder: '@SebastianBergmann\Diff\Output\UnifiedDiffOutputBuilder'

    Symplify\SmartFileSystem\Finder\FinderSanitizer: null
    Symplify\SmartFileSystem\FileSystemGuard: null

    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: null
    Symfony\Component\Console\Style\SymfonyStyle:
        factory: ['@Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory', 'create']

    Symplify\SmartFileSystem\SmartFileSystem: null
